version: '3'

services:
  gateway:
    container_name: gateway
    image: kong/kong-gateway:${KONG_VERSION:-latest}
    restart: unless-stopped
    ports:
      - 80:8000
      - 8443:8443
      - 8001:8001
      - 8444:8444
    volumes:
      - ./kong:/kong/declarative:ro
    environment:
      KONG_DATABASE: "off"
      KOND_DECLARATIVE_CONFIG: /kong/declarative/kong.yml
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: "0.0.0.0:8001, 0.0.0.0:8444 ssl"
    networks:
      - gateway_bridge

networks:
  gateway_bridge:
    # driver: overlay
    # attachable: true
    external: true 
