version: '3.8'

services:
  gateway:
    container_name: gateway
    image: kong:${KONG_VERSION:-latest}
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    restart: unless-stopped
    ports:
      - 80:8000
      - 443:8443
    configs:
      - source: kong-config
        target: /kong/declarative/kong.yml
    environment:
      KONG_DATABASE: "off"
      KONG_DECLARATIVE_CONFIG: /kong/declarative/kong.yml
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: "0.0.0.0:8001, 0.0.0.0:8444 ssl"
    networks:
      - gateway_bridge

configs:
  kong-config:
    file: ./kong/kong.yml

networks:
  gateway_bridge:
    driver: overlay
    external: true 
