version: '3.8'

services:
  prometheus:
    container_name: prometheus
    image: prom/prometheus
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.2"
          memory: 50M
      restart_policy:
        condition: on-failure
    restart: unless-stopped
    configs:
      - source: prometheus-config
        target: /etc/prometheus/prometheus.yml
    networks:
      - app
      - monitoring
      - gateway_bridge

  node_exporter:
    container_name: node_exporter
    image: prom/node-exporter
    restart: unless-stopped
    deploy:
      mode: global
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    networks:
      - monitoring

configs:
  prometheus-config:
    file: ./prometheus/prometheus.yml   

networks:
  app:
    driver: overlay
    external: true
  monitoring:
    driver: overlay
    external: true
  gateway_bridge:
    driver: overlay
    external: true
