version: '3.8'

services:
  prometheus:
    image: prom/prometheus:${PROMETHEUS_VERSION:-latest}
    command: ["--config.file=/etc/prometheus/prometheus.yml", "--storage.tsdb.path=/prometheus", "--web.console.libraries=/usr/share/prometheus/console_libraries", "--web.console.templates=/usr/share/prometheus/consoles", "--web.external-url=/prometheus/", "--web.route-prefix=/"]
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    configs:
      - source: prometheus-config
        target: /etc/prometheus/prometheus.yml
    networks:
      - app
      - monitoring
      - gateway_bridge

  node_exporter:
    image: prom/node-exporter:${NODE_EXPORTER_VERSION:-latest}
    deploy:
      mode: global
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    networks:
      - monitoring

configs:
  prometheus-config:
    file: ./prometheus/prometheus.yml   

networks:
  app:
    driver: overlay
    external: true
  monitoring:
    driver: overlay
    external: true
  gateway_bridge:
    driver: overlay
    external: true
