version: '3.8'

services:
  prometheus:
    container_name: prometheus
    image: prom/prometheus
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    restart: unless-stopped
    configs:
      - source: prometheus-config
        target: /etc/prometheus/prometheus.yml
    networks:
      - app
      - monitoring
      - gateway_bridge

  node_exporter:
    container_name: node_exporter
    image: prom/node-exporter
    restart: unless-stopped
    deploy:
      mode: global
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    networks:
      - monitoring

  loki:
    image: grafana/loki:${LOKI_VERSION:-latest}
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    volumes:
        - ./loki/loki.yml:/etc/config/loki.yml
        - .//loki/wal:/wal
    entrypoint:
        - /usr/bin/loki
        - -config.file=/etc/config/loki.yml
    ports:
        - 3100:3100
    networks:
        - database
        - app
        - gateway_bridge
        - monitoring

  grafana:
    image: grafana/grafana:${GRAFANA_VERSION:-latest}
    container_name: grafana
    restart: unless-stopped
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    depends_on:
      - loki
    ports:
      - 81:3000
    networks:
      - database
      - app
      - gateway_bridge
      - monitoring
    volumes:
      - grafana-volume:/var/lib/grafana
      - ./grafana/dashboards:/etc/grafana/provisioning/dashboards/
      - ./grafana:/etc/grafana/provisioning

configs:
  prometheus-config:
    file: ./prometheus/prometheus.yml   

volumes:
  grafana-volume:

networks:
  app:
    driver: overlay
    external: true
  monitoring:
    driver: overlay
    external: true
  database:
    # driver: overlay
    # attachable: true
    external: true
  gateway_bridge:
    driver: overlay
    external: true
