version: '3'

services:
  prometheus:
    container_name: prometheus
    image: prom/prometheus
    restart: unless-stopped
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090
    networks:
      - app
      - monitoring
      - gateway_bridge

  node_exporter:
    container_name: node_exporter
    image: prom/node-exporter
    restart: unless-stopped
    deploy:
      mode: global
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    ports:
      - 9100:9100
    networks:
      - monitoring    

  loki:
    image: grafana/loki
    volumes:
        - ../configs/loki/loki.yml:/etc/config/loki.yml
        - ../configs/loki/wal:/wal
    entrypoint:
        - /usr/bin/loki
        - -config.file=/etc/config/loki.yml
    ports:
        - 3100:3100
    networks:
        - database
        - app
        - gateway_bridge

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: unless-stopped
    depends_on:
      - loki
    ports:
      - 81:3000
    networks:
      - database
      - app
      - gateway_bridge
    volumes:
      - grafana-volume:/var/lib/grafana
      - ./grafana/dashboards:/etc/grafana/provisioning/dashboards/
      - ./grafana:/etc/grafana/provisioning

volumes:
  grafana-volume:

networks:
  app:
    # driver: overlay
    # attachable: true
    external: true
  monitoring:
    # driver: overlay
    # attachable: true
    external: true
  database:
    # driver: overlay
    # attachable: true
    external: true
  gateway_bridge:
    # driver: overlay
    # attachable: true
    external: true
