version: '3'

services:
  core:
    container_name: core
    image: ghcr.io/bitbyebit/calendar-parser-core-be:${CORE_BE_VERSION:-latest}
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.2"
          memory: 50M
      restart_policy:
        condition: on-failure
    restart: unless-stopped
    command: ["java", "-jar", "/srv/calendar-parser-core-be.jar"]
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      PARSER_URL: ${PARSER_URL}
      AUTHENTICATOR_URL: ${AUTHENTICATOR_URL}
    networks:
      - app
      - gateway_bridge
    depends_on:
      - parser
      - authenticator
    
  parser:
    container_name: parser
    image: ghcr.io/bitbyebit/calendar-parser-parser:${PARSER_VERSION:-latest}
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.2"
          memory: 50M
      restart_policy:
        condition: on-failure
    restart: unless-stopped
    command: ["java", "-jar", "/srv/calendar-parser-parser.jar"]
    networks:
      - app

  authenticator:
    container_name: authenticator
    image: ghcr.io/bitbyebit/calendar-parser-authenticator:${AUTHENTICATOR_VERSION:-latest}
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.2"
          memory: 50M
      restart_policy:
        condition: on-failure
    restart: unless-stopped
    command: ["java", "-jar", "/srv/calendar-parser-authenticator.jar"]
    secrets:
      - source: firebase-credential
        target: /srv/calendar-parser-e0e69-firebase-adminsdk-r7i9e-68f54358ea.json
    environment:
      FIREBASE_CREDENTIAL_PATH: ${FIREBASE_CREDENTIAL_PATH}
    networks:
      - app

secrets:
  firebase-credential:
    file: ./firebase/calendar-parser-e0e69-firebase-adminsdk-r7i9e-68f54358ea.json

networks:
  app:
    driver: overlay
    external: true
  gateway_bridge:
    driver: overlay
    external: true
    