version: '3.8'

services:
  postgres:
    container_name: postgres
    image: postgres
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints: [node.role == manager]
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        POSTGRES_DB: ${POSTGRES_DB}
    networks:
      - database
      - app

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    restart: unless-stopped
    depends_on:
      - postgres
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    environment:
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
    networks:
      - database
      - gateway_bridge

volumes:
  postgres-data:
  pgadmin-data:

networks:
  app:
    driver: overlay
    external: true
  database:
    driver: overlay
    external: true
  gateway_bridge:
    driver: overlay
    external: true

