version: '3'

services:
  postgres:
    container_name: postgres
    image: postgres
    restart: unless-stopped
    ports:
      - 5432:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    environment:
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        POSTGRES_DB: ${POSTGRES_DB}
    networks:
      - database
      - app

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    restart: unless-stopped
    depends_on:
      - postgres
    ports:
      - 5050:80
    volumes:
      - ./pgadmin-data:/var/lib/pgadmin
    environment:
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
    networks:
      - database
      - gateway_bridge

networks:
  app:
    # driver: overlay
    # attachable: true
    external: true
  database:
    # driver: overlay
    # attachable: true
    external: true
  gateway_bridge:
    # driver: overlay
    # attachable: true
    external: true

