version: '3'

services:
  postgres:
    container_name: postgres
    image: postgres
    restart: unless-stopped
    ports:
      - 5432:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    environment:
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        POSTGRES_DB: ${POSTGRES_DB}
    networks:
      - database
      - app

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    restart: unless-stopped
    depends_on:
      - postgres
    ports:
      - 5050:80
    volumes:
      - ./pgadmin-data:/var/lib/pgadmin
    environment:
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
    networks:
      - database
      - gateway_bridge

  loki:
    image: grafana/loki
    volumes:
        - ../configs/loki/loki.yml:/etc/config/loki.yml
        - ../configs/loki/wal:/wal
    entrypoint:
        - /usr/bin/loki
        - -config.file=/etc/config/loki.yml
    ports:
        - 3100:3100
    networks:
        - database
        - app

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: unless-stopped
    depends_on:
      - postgres
      - loki
    ports:
      - 81:3000
    networks:
      - database
      - app
    volumes:
      - grafana-volume:/var/lib/grafana
      - ./grafana/dashboards:/etc/grafana/provisioning/dashboards/
      - ./grafana:/etc/grafana/provisioning

networks:
  app:
    # driver: overlay
    # attachable: true
    external: true
  database:
    # driver: overlay
    # attachable: true
    external: true
  gateway_bridge:
    # driver: overlay
    # attachable: true
    external: true

volumes:
  grafana-volume:

