version: '3'

services:
  agent:
    container_name: agent
    image: portainer/agent:${PORTAINER_AGENT_VERSION:-latest}
    deploy:
      mode: global
      placement:
        constraints: [node.platform.os == linux]
      restart_policy:
        condition: on-failure
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    networks:
      - portainer

  portainer:
    container_name: portainer
    image: portainer/portainer-ce:${PORTAINER_CE_VERSION:-latest}
    command: -H tcp://agent:9001 --tlsskipverify
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]
      restart_policy:
        condition: on-failure
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer-data:/data
    networks:
      - portainer
      - gateway_bridge

volumes:
  portainer-data:

networks:
  portainer:
    driver: overlay
    external: true
  gateway_bridge:
    driver: overlay
    external: true 
